alumniportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static #
from django.conf import settings #

urlpatterns = [
    path('admin-site/', admin.site.urls),
    path('admin/',include('adminPortal.urls') ),
    path('',include('users.urls')),
    path('chat/',include('chat.urls')),
    path('post/', include('post.urls')),
    path('faq/', include('faq.urls')),
    path('groups/', include('groups.urls')),
    path('events/', include('events.urls')),
]
if settings.DEBUG: #
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.index ,name='faq'),
    path('create-question/', views.create_question, name='create_question'),
    path('load-question/<index>', views.load_question, name='load_question'),
    path('question/<id>/', views.question_detail, name='detail_question'),
    path('create-ans/<id>/', views.create_answer, name='create_answer'),
    path('ans-from-alumni', views.get_best4, name='ans-from-alumni'),
    path('upvote/', views.upvote, name='upvote'),
    path('downvote/', views.downvote, name='downvote'),
    path('accept-answer/', views.accept_answer, name='accept-answer'),
    path('delete/<id>/', views.delete_faq, name='delete-faq'),
    path('report/<id>/', views.report_faq, name='report-faq'),
]

users/urls.py
from os import name
from django.urls import path 

from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('signin/', views.sign_in, name='signin'),
  path('signout/', views.sign_out, name='signout'),
  path('signup-details/', views.signup_details, name='signup-details'),
  path('update-details/', views.update_profile, name='update-details'),
  path('callback', views.callback, name='callback'),
  #path('test',views.test),
  #path('test-signup/<name>/<email>',views.test_signup),
  # path('test-signin/<name>/',views.test_signin),
  path('follow/',views.follow),
  path('unfollow/',views.unfollow),
  path('followers/',views.followers),
  path('following/',views.following),
  #path('account',views.account),
  path('account/<username>/', views.profile , name='account'),
  path('details/',views.details,name="details"),
  # path('update/profile/',views.updateProfile,name="update-profile"),
  path('account/experience/<action>/', views.experience, name='experience'),
  path('account/project/<action>/', views.project, name='project'),
  path('account/education/<action>/', views.education, name='education'),
  path('account/job/<action>/', views.pastjobs, name='job'),
  path('account/change-profile-img/',views.update_photo, name="change-profile-img"),
  path('account/contact/update/',views.update_contact, name="update-contact"),

  path('search-sugg/',views.search_sugg, name="search-sugg"),
  path('search/',views.search_res,name="search"),
  # path('search/',views.filter_list,name="filter"),

  path('get-suggestions/',views.suggestions, name = 'suggestions')

]

users/models.py
from time import perf_counter, time
from django.db import models
from django.contrib.auth.models import User
import re
from datetime import date, datetime
import django.utils.timezone as timezone
# Create your models here.

def profile_image_path(instance, filename):
    ext = filename.split('.')[-1]
    if instance.user.username:
        return 'images/profile_imgs/'+'{}_{}.{}'.format(instance.user.username,re.sub(r'[^\w]', '', "%s"%(datetime.now().time())) ,ext)

class Account(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE, related_name='account')
    name=models.CharField(max_length=100)
    email=models.EmailField()
    description=models.CharField(max_length=400, null=True, blank=True)
    branch=models.ForeignKey('Branch',related_name='students', on_delete=models.CASCADE, null=True, blank=True)
    start_year=models.IntegerField(default=2019)
    graduation_year=models.IntegerField(default=2023)
    following=models.ManyToManyField('Account',related_name='followers', blank=True)
    profile_img=models.ImageField(upload_to=profile_image_path,null=True, blank=True)
    last_active=models.DateTimeField(null=True,default=datetime.now)
    organization=models.ForeignKey('Organization',related_name='employees', on_delete=models.CASCADE, blank=True, null=True)
    designation = models.ForeignKey('Designation',related_name='employees', on_delete=models.CASCADE, blank=True, null=True)
    is_alumni = models.BooleanField(default=False)
    signup_done = models.BooleanField(default=False)
    @property
    def profile_img_url(self):
        if self.profile_img:
            return self.profile_img.url
        else:
            return "/static/img/default-avatar.svg"
    def current_year(self):
        if timezone.now().month<7:
            return (self.start_year-timezone.now().year)*-1
        else: 
            return 1+((self.start_year-timezone.now().year)*-1)
    def __str__(self):
        return self.name

class GenericExperience(models.Model):
    description=models.CharField(default="",max_length=255)
    start_date=models.DateField(null=True, blank=True)
    end_date=models.DateField(null=True, blank=True)

    class Meta:
        abstract = True

    def get_duration(self):
        duration={}
        # months = (self.end_date.year - self.start_date.year)*12+ (self.end_date.month - self.start_date.month)
        if self.end_date:
            duration["years"]=(self.end_date.year - self.start_date.year)
            duration["months"]=(self.end_date.month - self.start_date.month)
        else:
            duration["years"]=(date.today().year - self.start_date.year)
            duration["months"]=(date.today().month - self.start_date.month)
        return duration

    def get_start_date(self):
        if(self.start_date):
            return self.start_date.strftime('%b %Y')
        else:
            return ""
    def get_end_date(self):
        if(self.end_date):
            return self.end_date.strftime('%b %Y')
        elif self.start_date:
            return 'Present'
        else:
            return ""
   
class Contact(models.Model):
    user=models.OneToOneField(Account, on_delete=models.CASCADE, related_name="contact")
    gmail=models.EmailField(blank=True, null=True)
    outlook=models.EmailField(blank=True, null=True)
    linkedin=models.URLField(blank=True, null=True)
    mobile=models.IntegerField(blank=True, null=True)

class Organization(models.Model):
    name=models.CharField(max_length=150)

    def __str__(self):
        return self.name
class Designation(models.Model):
    title=models.CharField(max_length=150)
    
    def __str__(self):
        return self.title

class Branch(models.Model):
    name=models.CharField(max_length=150)
    
    def __str__(self):
        return self.name

class Institute(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class PastJobs(GenericExperience):
    user=models.ForeignKey(Account, on_delete=models.CASCADE, related_name="jobs")
    organization=models.ForeignKey(Organization, on_delete=models.CASCADE, related_name="jobs")
    designation=models.ForeignKey(Designation,on_delete=models.CASCADE, related_name="jobs")

class Experience(GenericExperience):
    user=models.ForeignKey(Account, on_delete=models.CASCADE, related_name="experiences")
    experience=models.CharField(max_length=100)
    organization=models.ForeignKey(Organization, on_delete=models.CASCADE, null=True, blank=True, related_name="experiences")

class Project(GenericExperience):
    user=models.ForeignKey(Account, on_delete=models.CASCADE, related_name="projects")
    project=models.CharField(max_length=100)
    team = models.ManyToManyField(Account, related_name='shared_project')

class Education(GenericExperience):
    user=models.ForeignKey(Account, on_delete=models.CASCADE, related_name="educations")
    education=models.CharField(max_length=100)
    institute=models.ForeignKey(Institute, on_delete=models.CASCADE, related_name="educations", null=True)

users/forms.py
from typing import Text
from .models import Account, Contact, Designation, Education, Experience, Organization, Project,PastJobs
from django import forms
from django.forms import widgets
from django.contrib.auth.models import User

class SignupForm(forms.Form):
    dob=forms.DateField(label='Date of Birth: ',widget=widgets.DateInput(attrs={'type':'date'}))
    company=forms.CharField(label='Company: ', max_length=50)
    profile_img=forms.ImageField(label='')
    phone=forms.CharField(max_length=13)
    location=forms.CharField(max_length=25)

class FormattedModelForm(forms.ModelForm):
    def as_myformat(self):
        return self._html_output(
            normal_row='''<div class="form-group">
                            <div class="row">
                                <label class="control-label col-sm-3">%(label)s</label>
                                <div class="col-sm-5">
                                    %(field)s
                                    %(errors)s
                                </div>
                                <div class="col-sm-4"></div>
                            </div>
                            <div class="row">
                                %(help_text)s
                            </div>
                    </div>''',
            error_row='<span class="error">%s</span>',
            row_ender='</div>',
            help_text_html='<small class="gray offset-3 col-sm-9">%s</small>',
            errors_on_separate_row=False,
        )

class UserUpdateForm(FormattedModelForm):        #for updating info of the user on the profile page
    email=forms.EmailField()
    class Meta:
         model = User                            
         fields = ['username','email']

class ExperienceForm(FormattedModelForm):
    class Meta:
        model=Experience
        exclude=['user']
        widgets = {
            'start_date': widgets.DateInput(attrs={'type': 'date','class':'w-52 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}),
            'end_date': widgets.DateInput(attrs={'type': 'date','class':'w-52 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}),
            'experience':widgets.TextInput(attrs={'class':'w-52 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'})
        }

# class PastJobsForm(FormattedModelForm):
#     class Meta:
#         model=PastJobs
#         exclude=['user']
#         widgets = {
#             'start_date': widgets.DateInput(attrs={'type': 'date','class':'w-64 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}),
#             'end_date': widgets.DateInput(attrs={'type': 'date','class':'w-64 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}),
#             'organization':widgets.Select(attrs={'class':'w-64 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}),
#             'designation':widgets.Select(attrs={'class':'w-64 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}),
#             'description':widgets.Textarea(attrs={'class':'w-64 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'})
#         }

class PastJobsForm(forms.Form):
    organization=forms.CharField(max_length=100,widget=widgets.TextInput(attrs={'class':'w-52 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}))
    designation=forms.CharField(max_length=100,widget=widgets.TextInput(attrs={'class':'w-52 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}))
    description=forms.CharField(max_length=255,widget=widgets.Textarea(attrs={'class':'w-52 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}))
    start_date=forms.DateField(label='Start Date',widget=widgets.DateInput(attrs={'type': 'date','class':'w-52 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}))
    end_date=forms.DateField(label='End Date',widget=widgets.DateInput(attrs={'type': 'date','class':'w-52 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}),required=False)

class ProjectForm(FormattedModelForm):
    class Meta:
        model=Project
        fields=['project']
    
class EducationForm(FormattedModelForm):
    class Meta:
        model=Education
        fields=['education']

class ContactUpdateForm(FormattedModelForm):        #for updating info of the user on the profile page
    class Meta:
         model = Contact                           
         fields = ['gmail','mobile','outlook','linkedin']

class ImageUploadForm(forms.Form):
    image = forms.ImageField()

users/templates/accounts-results-partial.html
{# accounts-results-partial.html #}
<head>
 <link rel="stylesheet" href="/static/stylesheets/style-base.css">
</head>

<div> 
  {% if accounts %}
    <ul class="">
    {% for account in accounts %}
    <li class="flex bg-gray-100 rounded-1g h-16 w-96 ml-9 mr-5 mt-2.5 mb-2.5"><img class="mt-4 mb-4 ml-4 h-8 w-8"  src="{{account.profile_img_url}}"><a class="font-medium  non-italic text-x1  h-5 mt-4 ml-3" href="{% url 'account' account.email %}">{{ account.name }}</a></li>
    {% endfor %}
    </ul>
  {% else %}
   <!-- <p>No accounts found.</p>  -->
  {% endif %}
</div>  

users/templates/add_form.html
<!--<form method="POST" action="{% url 'add-experience'%}" class="grid grid-cols-1 add_experience mx-16 p-5 bg-white flex grid grid-cols-3" style="display: none;">
    {% csrf_token%}
    {{ e_form.non_field_errors }}
    <div class="mr-5 mt-2">
        {{ e_form.experience.errors }}
        <label class="text-gray-400" for="{{ e_form.experience.id_for_label }}">Role</label><br>
        {% comment %} <input class="w-64 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="role" type="text" > {% endcomment %}
        {{e_form.experience}}
    </div>
    <div class="mr-5 mt-2">
        {{ e_form.start_date.errors }}
        <label class="text-gray-400" for="{{ e_form.start_date.id_for_label }}">Start Date</label><br>
        {% comment %} <input class="w-64 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="role" type="text" > {% endcomment %}
        {{e_form.start_date}}
    </div>
    <div class="mr-5 mt-2">
        {{ e_form.end_date.errors }}
        <label class="text-gray-400" for="{{ e_form.end_date.id_for_label }}">End Date</label><br>
        {% comment %} <input class="w-64 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="role" type="text" > {% endcomment %}
        {{e_form.end_date}}
    </div>
    <input type="submit">
</form>
-->
    <div  class="mx-9 sm:ml-16 mr-16 lg:mr-64  add_experience mt-3" style="display: none;" >
        <form id="exp" method="POST" action="{% url 'add-experience' %}" class="flex bg-white justify-start grid sm:grid-cols-3 xl:grid-cols-4 p-5">
            {% csrf_token%}
            {{ e_form.non_field_errors }}
            <div class="mr-5 mt-2">
                {{ e_form.experience.errors }}
                <label class="text-gray-400" for="{{  e_form.experience.id_for_label }}">Role</label><br>
                {% comment %} <input class="w-64 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="role" type="text" > {% endcomment %}
                {{e_form.experience}}
            </div>
            <div class="mr-5 mt-2">
                {{ e_form.start_date.errors }}
                <label class="text-gray-400" for="{{ e_form.start_date.id_for_label }}">Start Date</label><br>
                {% comment %} <input class="w-64 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="role" type="text" > {% endcomment %}
                {{e_form.start_date}}
            </div>
            <div class="mr-5 mt-2">
                {{ e_form.end_date.errors }}
                <label class="text-gray-400" for="{{ e_form.end_date.id_for_label }}">Start Date</label><br>
                {% comment %} <input class="w-64 sm:w-full bg-accent-faded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="role" type="text" > {% endcomment %}
                {{e_form.end_date}}
            </div>
            <div class="col"><button type="submit" name="submit" value="submit" class="bg-accent w-28 text-white rounded-md py-1 px-0.5 mt-9">Add</button></div>
        </form>
    </div>
    <div  class="add_job bg-white mx-9 sm:ml-16 mr-16 lg:mr-64  mt-3 overflow-hidden">
        <form method="POST" action="{% url 'add-job'%}" id="form1" class="flex justify-start grid md:grid-cols-3 xl:grid-cols-4 p-5">
            {% csrf_token%}
            {{ j_form.non_field_errors }}
            <div class="mr-5 mt-2 ">
                {{ j_form.designation.errors }}
                <label class="text-gray-400" for="{{ j_form.designation.id_for_label }}">Role</label><br>
                {{j_form.designation}}
            </div>
            <br class="sm:hidden">
            <div class=" mr-5 mt-2">
                {{ j_form.organization.errors }}
                <label class="text-gray-400" for="{{ j_form.organization.id_for_label }}">Organization</label><br>
                {{j_form.organization}}
            </div><br class="sm:hidden">
            <div class="mr-5 mt-2">
                {{ j_form.start_date.errors }}
                <label class="text-gray-400" for="{{ j_form.start_date.id_for_label }}">Start Date</label><br>
                {{j_form.start_date}}
            </div><br class="sm:hidden">
            <div class="mr-5 mt-2">
                {{ j_form.end_date.errors }}
                <label class="text-gray-400" for="{{ j_form.end_date.id_for_label }}">End Date</label><br>
                {{j_form.end_date}}
            </div>
            <div class=" mr-5 mt-2 col-span-2">
                {{ j_form.description.errors }}
                <label class="text-gray-400" for="{{ j_form.description.id_for_label }}">Description</label><br>
                {{j_form.description}}
            </div>
            <div class="">
                <button type="submit" name="submit" value="submit" class="bg-accent w-28 text-white rounded-md py-1 px-0.5 mt-7">Add</button>
            </div>
        </form>
    </div>
<script>
$('#form1').on('submit', function(e){
    e.preventDefault();
    $.ajax({
            type : "POST", 
            url:"{% url 'add-job'%}",
            data: {
            designation: $('#id_designation').val(),
            organization: $('#id_organization').val(),
            description: $('#id_description').val(),
            start_date: $('#id_start_date').val(),
            end_date: $('#id_end_date').val(),
            csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val(),
            dataType: "json",
            },
            cache: false,
            success: function(data){
            $('#form1')[0].reset();
            alert("submission success") /* response message */
            $("#overlay").css('display', 'none');
            },
            failure: function() {
                alert("submission failed")
            }
        });
    }); 
    function submitform(e,formid){
    e.preventDefault();
    var frm = $(formid);

    $.ajax({
        type:'POST',
        url:"{% url 'add-experience'%}",
        data:frm.serialize(),
        success:function(response){
        $(formid)[0].reset();
        alert('You Experience has been added')
        $("#overlay").css('display', 'none');
        },
        error:function(response){
            alert(response["responseJSON"]["error"]);
        }
    })
}

$('#exp').on('submit',(e)=>{submitform(e,'#exp')}) 
</script>

users/templates/search_box.html
<form id="search-form" class="bg-accent-faded h-10 md:w-1/3 w-1/2 flex items-center ml-4 sm:ml-8 md:ml-16 rounded-sm relative" action="/search/" method="GET">
    <input type="text" name="query" id="search-input" placeholder="Search..." class="flex-1 ml-4 bg-transparent min-w-0" autocomplete="off">
    <button class="p-0" id="search-submit"><img src="/static/img/search.svg" alt="" class="h-10 w-10 px-2 bg-accent rounded-sm"></button>
    <div id="search-sugg-wrp" class="absolute w-screen -ml-4 sm:w-full sm:ml-0 bg-white shadow-lg top-10 pb-2 hidden"></div>
</form>

<template id="search-sugg-cat-tmp">
    <div class="border-t-2 border-gray-200 border-solid pl-8 pr-5 pt-4 pb-6">
        <p class="search-sugg-cat text-gray-400 text-sm my-1">GROUPS</p>
        <div class="search-sugg-entries">

        </div>
    </div>
</template>

<template id="search-sugg-entry-tmp">
    <div>
        <a class="search-sugg-url bg-gray-100 mt-2.5 flex items-center h-16 px-4 rounded-lg cursor-pointer">
            <img src="{{user.account.profile_img_url}}" class="search-sugg-img h-9 w-9 rounded-full object-cover">
            <div class="ml-2">
                <p class="search-sugg-title text-sm">UX/UI Designer</p>
                <p class="search-sugg-subt text-xs">126 members</p>
            </div>
        </a>
    </div>
</template>

{% block scripts %}
<script>
    $(document).ready(function(){
        $('#search-submit').on('click',function(e){
            e.preventDefault()
            var input = $('#search-input').val()
            sessionStorage.setItem('query',input)
            $('#search-form').submit();
        })
        $('#search-input').on('keyup', function(e){
            if(e.keyCode==13){
                var input = $(this).val()
                sessionStorage.setItem('query',input)
                $('#search-form').submit();
            }else{
                $.ajax({
                    url:'/search-sugg/',
                    data:{'query':$(this).val()},
                    dataType:'json',
                    success: (data)=>{
                        if(data.query!=$(this).val())return;
                        console.log(data);
                        $('#search-sugg-wrp').removeClass('hidden');
                        $('#search-sugg-wrp').html("");
                        for(const cat in data.results){
                            if(!data.results[cat].length)continue;
                            const tempWrp = $('#search-sugg-cat-tmp')[0];
                            const d = tempWrp.content.cloneNode(true);
                            $('.search-sugg-cat',d).text(cat.toUpperCase());
                            let ctr=1;
                            for(const entry of data.results[cat]){
                                const tmp = $('#search-sugg-entry-tmp')[0];
                                const p = tmp.content.cloneNode(true);;
                                $('.search-sugg-title',p).text(entry.title);
                                $('.search-sugg-subt',p).text(entry.subtitle);
                                $('.search-sugg-img',p).attr('src',entry.img);
                                $('.search-sugg-url',p).attr('href',entry.url);
                                $('.search-sugg-entries',d).append(p);
                                ctr++;
                                if(ctr>2)break;
                            }
                            $('#search-sugg-wrp').append(d);
                        }
                    },
                    error: (err)=>{
                        console.log(err);
                    }
                })
            }
        })
        $(window).on('click',function(e){
            $('#search-sugg-wrp').addClass('hidden');
        })
    });
</script>
{% endblock %}

users/templates/update_forms.html
{% comment %} <form method="POST" class="update_job_form bg-white p-5" style="display: none;">
  {% csrf_token %}
 {{j_form}}
  {% if user == curr_user.user %}
  <button class="h-5 w-5 submit_update" type="submit">Submit</button> 
  {% endif %}
</form> {% endcomment %}
    <div data-id=""  class="update_job_form  bg-white mx-9 sm:ml-16 mr-16 lg:mr-64  mt-3 overflow-hidden" style="display: none;">
        <form  method="PUT" action="{% url 'add-job'%}" id="formedit" class="flex justify-start grid md:grid-cols-3 xl:grid-cols-4 p-5">
            {% csrf_token%}
            {{ j_form.non_field_errors }}
            <div class="mr-5 mt-2 ">
                {{ j_form.designation.errors }}
                <label class="text-gray-400" for="{{ j_form.designation.id_for_label }}">Role</label><br>
                {{j_form.designation}}
            </div>
            <br class="sm:hidden">
            <div class=" mr-5 mt-2">
                {{ j_form.organization.errors }}
                <label class="text-gray-400" for="{{ j_form.organization.id_for_label }}">Organization</label><br>
                {{j_form.organization}}
            </div><br class="sm:hidden">
            <div class="mr-5 mt-2">
                {{ j_form.start_date.errors }}
                <label class="text-gray-400" for="{{ j_form.start_date.id_for_label }}">Start Date</label><br>
                {{j_form.start_date}}
            </div><br class="sm:hidden">
            <div class="mr-5 mt-2">
                {{ j_form.end_date.errors }}
                <label class="text-gray-400" for="{{ j_form.end_date.id_for_label }}">End Date</label><br>
                {{j_form.end_date}}
            </div>
            <div class=" mr-5 mt-2 col-span-2">
                {{ j_form.description.errors }}
                <label class="text-gray-400" for="{{ j_form.description.id_for_label }}">Description</label><br>
                {{j_form.description}}
            </div>
            <div class="">
                <button type="submit" name="submit" value="submit" class="bg-accent w-28 text-white rounded-md py-1 px-0.5 mt-7">Add</button>
            </div>
        </form>
    </div>
<form method="POST" class="update_ex_form bg-white p-5" style="display: none;">
  {% csrf_token %}
  {{e_form}}
  {% if user == curr_user.user %}
  <button class="btn btn-outline-info submit_update" type="submit">Submit</button> 
  {% endif %}
</form>
{% block scripts %}
<script src="/static/scripts/profile.js"></script>
{% endblock %}

<form method="POST" class="update_contact_form">
  {%csrf_token%}
  {{ ct_form.as_myformat }}
  
  {% if user == curr_user.user %}
  <button class="btn btn-outline-info submit_update" type="submit">Submit</button> 
  {% endif %}
</form>
{% comment %} <form method="POST" class="update_p_form" >
  {%csrf_token%}
  {{ p_form.as_myformat }}
  
  {% if user == curr_user.user %}
  <button class="btn btn-outline-info submit_update" type="submit">Submit</button> 
  {% endif %}
</form> {% endcomment %}
{% comment %} 
<form method="POST" class="update_edu_form" >
  {%csrf_token%}
  {{ edu_form.as_myformat }}
  
  {% if user == curr_user.user %}
  <button class="btn btn-outline-info submit_update" type="submit">Submit</button> 
  {% endif %}
</form> {% endcomment %}

<script>
$('#formedit').on('submit', function(e){
    e.preventDefault();
    $.ajax({
            type : "PUT", 
            url:"{% url 'update-job'%}",
            data: {
            designation: $('#id_designation').val(),
            organization: $('#id_organization').val(),
            description: $('#id_description').val(),
            start_date: $('#id_start_date').val(),
            end_date: $('#id_end_date').val(),
            id:$('.update_job_form').attr('data-id'),
            csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val(),
            dataType: "json",
            },
            cache: false,
            success: function(data){
            $('#formedit')[0].reset();
            alert("submission success") /* response message */
            $("#overlay").css('display', 'none');
            },
            failure: function() {
                alert("submission failed")
            }
        });
    });  
</script>