alumniportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static #
from django.conf import settings #

urlpatterns = [
    path('admin-site/', admin.site.urls),
    path('admin/',include('adminPortal.urls') ),
    path('',include('users.urls')),
    path('chat/',include('chat.urls')),
    path('post/', include('post.urls')),
    path('faq/', include('faq.urls')),
    path('groups/', include('groups.urls')),
    path('events/', include('events.urls')),
]
if settings.DEBUG: #
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.index ,name='faq'),
    path('create-question/', views.create_question, name='create_question'),
    path('load-question/<index>', views.load_question, name='load_question'),
    path('question/<id>/', views.question_detail, name='detail_question'),
    path('create-ans/<id>/', views.create_answer, name='create_answer'),
    path('ans-from-alumni', views.get_best4, name='ans-from-alumni'),
    path('upvote/', views.upvote, name='upvote'),
    path('downvote/', views.downvote, name='downvote'),
    path('accept-answer/', views.accept_answer, name='accept-answer'),
    path('delete/<id>/', views.delete_faq, name='delete-faq'),
    path('report/<id>/', views.report_faq, name='report-faq'),
]

groups/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name="groups"

urlpatterns=[
    path('', views.all_groups ,name='groups'),
    path('page/<id>/',views.group,name='group'),
    path('create-edit/', csrf_exempt(views.create_edit_group) ,name='create'),
    path('delete/<id>/', csrf_exempt(views.delete_group) ,name='delete'),
    path('rename/<id>/', csrf_exempt(views.rename_group) ,name='rename'),
    path('change-cover/<id>/', csrf_exempt(views.change_cover_group), name='change_cover'),
    path('join-group/<id>/', csrf_exempt(views.join_group), name='join'),
    path('leave-group/<id>/', csrf_exempt(views.leave_group), name='leave'),
    path('get-members/<id>/', csrf_exempt(views.get_members), name='members'),
]

groups/models.py
from django.db import models
from users.models import Account
# Create your models here.
class Group(models.Model):
    title = models.CharField(max_length = 75)
    cover_image = models.ImageField(upload_to = 'images/groups', blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    members = models.ManyToManyField(Account, related_name='groups', blank=True)
    
    def __str__(self):
        return self.title
    
    @property 
    def member_count(self):
        return len(self.members.all())

groups/forms.py
from django.db.models import fields
from .models import Group
from django import forms

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['title','cover_image','description']

groups/views.py
import json
from groups.forms import GroupForm
from django.http.response import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from .models import Group
from post.forms import PostForm

@login_required
def all_groups(request):
    groups=Group.objects.all()
    return render(request, "all_groups.html", context={'groups':groups})

def group(request,id):
    group = get_object_or_404(Group,id=id)
    return render(request,'group.html',{'group':group,'postform': PostForm })
    
def create_edit_group(request):
    if not request.user.is_authenticated:
        return HttpResponse('Unauthorized', status=401)
    if request.method == 'POST':
        if request.GET.get('id',None)!=None:
            group_obj = get_object_or_404(Group,id=request.GET.get('id'))
            form = GroupForm(request.POST, request.FILES, instance=group_obj)
        else:
            form = GroupForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('/admin/groups/')
    return HttpResponse('Bad Request',status=400)

def delete_group(request,id):
    if not request.user.is_authenticated:
        return HttpResponse('Unauthorized', status=401)
    if request.method == 'POST':
        group = get_object_or_404(Group, id= id)
        group.delete()
        return HttpResponse('Success',status=200)
    return HttpResponse('Bad Request',status=400)

def rename_group(request, id):
    if not request.user.is_authenticated:
        return HttpResponse('Unauthorized', status=401)
    if request.method == 'POST':
        if request.POST.get('title'):
            group = get_object_or_404(Group, id= id)
            group.title = request.POST.get('title')
            group.save()
            return HttpResponse('Success',status=200)
    return HttpResponse('Bad Request',status=400)

def change_cover_group(request, id):
    if not request.user.is_authenticated:
        return HttpResponse('Unauthorized', status=401)
    if request.method == 'POST':
        form = GroupForm(request.POST, request.FILES, instance=get_object_or_404(Group,id=id))
        if form.is_valid():
            form.save()
            return HttpResponse('Success',status=200)
    return HttpResponse('Bad Request',status=400)

def join_group(request,id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            group = get_object_or_404(Group, id=id)
            group.members.add(request.user.account)
            return HttpResponse('Success',status=200)
        else:
            return HttpResponse('Bad Request',status=400)
    return HttpResponse('Unauthorized', status=401)

def leave_group(request,id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            group = get_object_or_404(Group, id=id)
            group.members.remove(request.user.account)
            return HttpResponse('Success',status=200)
        else:
            return HttpResponse('Bad Request',status=400)
    return HttpResponse('Unauthorized', status=401)

def get_members(request,id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            group = get_object_or_404(Group, id=id)
            members={'alumni':[],'common':[],'other':[]}
            for member in group.members.all():
                m = {}
                m['username']=member.user.username
                m['profile_img']=member.profile_img_url
                m['name']=member.name
                if member.user.id == request.user.id:
                    m['is_followed']=True
                    members['common'].append(m)
                    continue
                m['is_followed']=member in request.user.account.following.all()
                if member.is_alumni:
                    members['alumni'].append(m)
                else:
                    ctr=0
                    for grp in request.user.account.groups.all():
                        if member in grp.members.all() and grp.id!=group.id:
                            ctr+=1
                    if ctr:
                        members['common'].append(m)
                    else:
                        members['other'].append(m)
            return HttpResponse(json.dumps(members),status=200)
        else:
            return HttpResponse('Bad Request',status=400)
    return HttpResponse('Unauthorized', status=401)


 

groups/templates/all_groups.html
{% extends "base.html" %}

{% block head%}
    <title>Groups | Alumni Portal</title>
    <style>
        #right-pane{
            display: none !important;
        }
        #content{
            width: 100% !important;
            padding-right: 3.5%;
            padding-left: 3.5%;
        }
    </style>
{% endblock%}

{% block content %}
    <div class="flex justify-center flex-wrap items-stretch">
        {% for group in groups%}
        <div class="group-thumbnail cursor-pointer w-64 mt-6 rounded mx-3 flex-grow sm:flex-grow-0 flex flex-col" data-id="{{group.id}}">
            <img src="{{group.cover_image.url}}" alt="" class="w-full h-52 sm:h-44 object-cover">
            <div class="flex flex-col items-center bg-white py-2 justify-between flex-grow px-5">
                <div class="flex-grow flex flex-col ">
                    <p class="text-md font-medium text-center">{{group.title}}</p>
                    <p class="member-count text-sm text-gray-500 text-center" data-id="{{group.id}}">{{group.member_count}} Members</p>
                </div>
                {% if user.account in group.members.all %}
                <div class="text-sm text-white bg-accent rounded py-0.5 px-6 mt-2" data-id="{{group.id}}">
                    Joined
                </div>
                {% else %}
                <div class="join-group text-sm text-white bg-accent rounded py-0.5 px-6 mt-2 cursor-pointer hover:opacity-90" data-id="{{group.id}}">
                    Join Group
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        <!-- {% if user.is_staff %}
        <div class="create-group cursor-pointer hover:opacity-90 w-64 mt-6 rounded mx-3 bg-white flex-grow sm:flex-grow-0 flex flex-col justify-center items-center self-strech" style="min-height: 288px;">
            <img src="/static/img/add.svg" alt="" class="h-16 w-16 object-cover">
            <p class="text-lg text-gray-500">Create</p>
        </div>
        {% endif %} -->
    </div>
{% endblock %}

{% block overlay %}
    <form action="/groups/create/" method="POST" enctype="multipart/form-data" id="create-group-form" class="bg-white rounded p-5 hidden w-full md:w-3/5 lg:w-2/5 h-screen md:h-auto flex-col" >
        {% csrf_token %}
        <div class="flex justify-between items-center m-2">
            <p class="text-xl">Create a Group</p>
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg" class="close-overlay cursor-pointer">
                <path opacity="0.8" d="M1 13L13 1M1 1L13 13" stroke="#111827" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>   
        </div>
        <input type="file" name="cover_image" accept="image/png, image/jpeg" id="create-group-img" class="hidden">
        <div id="create-group-prev" class="bg-gray-200 rounded h-60 mx-auto w-3/5 flex flex-col cursor-pointer items-center justify-center mt-3">
            <img src="/static/img/add.svg" alt="" class="h-16 w-16 object-cover rounded" >
            <p class="text-gray-400">Cover Image</p>
        </div>
        <div class="bg-gray-200 p-3 rounded mt-7">
            <input type="text" name="title" placeholder="Title" class="bg-transparent w-full">
        </div>
        <div class="bg-gray-200 p-3 rounded mt-7">
            <textarea name="description" placeholder="Description" style="resize: none;" class="bg-transparent w-full h-20"></textarea>
        </div>
        <input type="submit" value="Create" class="self-center bg-accent text-white py-2 px-10 rounded mt-7">
    </form>
{% endblock %}

{% block scripts %}
<script src="/static/scripts/groups.js"></script>
{% endblock %}

groups/templates/group.html
{% extends "base.html" %}

{% block head %}
<title>{{group.title}} | Alumni Portal</title>
<link rel="stylesheet" href="/static/stylesheets/style-group.css">
{% endblock %}

{% block content %}
<div>
    <div class="h-52 w-full bg-bluegray mt-5 relative">
        <img src="{{group.cover_image.url}}" class="w-full h-full object-cover" alt="">
        <a href="/groups/" class="bg-white rounded absolute top-2 left-2 h-9 w-9 flex items-center justify-center hover:opacity-90"><img src="/static/img/arrow-left.svg" alt="" class="w-9 h-5"></a>
        <button class="bg-white rounded absolute top-2 right-2 h-9 w-9 flex items-center justify-center"><img src="/static/img/dots-vertical.svg" alt="" class="w-9 h-5"></button>
    </div>
    <div class="w-full bg-white px-4 sm:px-9 pt-5 pb-5 flex flex-col justify-between" style="min-height: 210px;">
        <div class="flex flex-col md:flex-row">
            <div style="min-width: 200px;">               
                <div class="text-2xl font-medium mb-1">Design</div>
                <div class="text-xs">2 Members</div>
            </div>
            <div class="flex-grow md:ml-5">
                <div class="text-lg font-medium mb-1 hidden md:block">About</div>
                <div class="text-sm mt-4 md:mt-0">
                {{group.description}}
                </div>
            </div>
        </div>
        <div class="flex justify-between items-center mt-6">
            <div class="hidden md:block">
                <img src="/media/images/profile_imgs/arjundeyiitg.ac.in_144756544363.jpg" class="rounded-full h-8 w-8 inline object-cover">
                <span class="w-4/5 ml-4 text-gray-300">Share something with the group</span>
            </div>
            <div class="flex justify-between">
            <button class="create-post text-sm text-accent bg-accent-mid py-2 px-5 lg:mr-6 mr-2"><img src="/static/img/pencil.svg" class="pencil w-4 h-4 mr-1 inline">&nbsp;Create post</button>
            <button class="create-question text-sm text-accent bg-accent-mid py-2 px-5 "><img src="/static/img/information.svg" class="w-4 h-4 mr-1 inline">&nbsp;Ask Question</button>
            </div>
        </div>
    </div>
</div>

<div class="flex justify-around items-stretch bg-white rounded h-14 mt-6">
    <div class="group-tab cursor-pointer flex items-center justify-center text-lg text-accent group-tab-active" data-tab="post">Post</div>
    <div class="group-tab cursor-pointer flex items-center justify-center text-lg text-accent" data-tab="members">Members</div>
    <div class="group-tab cursor-pointer flex items-center justify-center text-lg text-accent" data-tab="questions">Questions</div>
</div>

<div data-tab="post" class="group-tab-content w-full sm:w-11/12 mx-auto">
    {% include "posts.html" %}
    <script class='feed-tag' data-id="{{group.id}}" type='text'>{{group.title}}</script>
</div>

<div data-tab="members" class="group-tab-content w-full hidden">
    {% include "group_members.html" %}
</div>

<div data-tab="questions" class="group-tab-content w-full sm:w-11/12 mx-auto hidden">
    {% include "faq-content.html" %}
    <script class='faq-feed-tag' data-id="{{group.id}}" type='text'>{{group.title}}</script>
</div>

{% endblock %}

{% block right-pane %}
    {% include "user_groups.html" %}
{% endblock %}

{% block overlay %}
    {% include "post_create.html" %}
    {% include "comment.html" %}
    {% include "faq_create.html" %}
{% endblock%}

{% block scripts %}
<script>
    $(document).ready(function(){
        $('.group-tab').on('click', function(e){
            let tabName = $(this).attr('data-tab');
            location.hash=tabName;
            $('.group-tab-content').addClass('hidden');
            $(`.group-tab-content[data-tab=${tabName}]`).removeClass('hidden');
            $('.group-tab').removeClass('group-tab-active');
            $(`.group-tab[data-tab=${tabName}]`).addClass('group-tab-active');
        });

        if(location.hash)
            $(`.group-tab[data-tab=${location.hash.slice(1)}]`).click();
    });
</script>
{% endblock %}

groups/templates/group_members.html
<div class="w-full flex flex-col items-center mt-5">

    <div class="w-full flex flex-col-reverse sm:flex-row items-center p-3 sm:p-5 bg-white mb-6 rounded">
        <div class="three-member-imgs hidden mr-3 sm:flex">
            <img src="" alt="" class="rounded-full p-0.5 bg-white object-cover h-10 w-10">
            <img src="" alt="" class="rounded-full p-0.5 bg-white object-cover h-10 w-10 -ml-4">
            <img src="" alt="" class="rounded-full p-0.5 bg-white object-cover h-10 w-10 -ml-4">
        </div>
        <p class="text-gray-500 text-sm flex-shrink-1 mt-2 sm:mt-0">
            <span>{{group.member_count}} Members </span>
            <span class="hidden md:inline">are part of this group</span>
        </p>
        <form id="search-form" class="bg-accent-faded flex flex-grow self-stretch rounded sm:self-center items-center sm:ml-6 md:ml-14 p-2" action="">
            <img src="/static/img/search.svg" alt="" class="mx-1 md:mx-3 h-5 w-5">
            <input type="text" name="" id="member-search-input" placeholder="Search Members..." class="flex-1 bg-transparent min-w-0">
        </form>
    </div>

    <div class="w-full sm:w-5/6 rounded bg-white px-6 py-4 mb-4" >
        <p> Alumni </p>
        <div class="w-full members-section" id="members-alumni">
            
        </div>
    </div>

    <div class="w-full sm:w-5/6 rounded bg-white px-6 py-4 mb-4" >
        <p> Members with common groups</p>
        <div class="w-full members-section" id="members-common">
            
        </div>
    </div>

    <div class="w-full sm:w-5/6 rounded bg-white px-6 py-4 mb-4" >
        <p> Members </p>
        <div class="w-full members-section" id="members-other">
            
        </div>
    </div>

    <div class="w-full sm:w-5/6 rounded bg-white px-6 py-4 mb-4 hidden" >
        <p> Results </p>
        <div class="w-full" id="members-results">   

        </div>
    </div>

</div>

<template id="member-entry-temp">
    <div class="flex justify-between items-center py-4">
        <div class="flex items-center justify-start">
            <img src="{{user.account.profile_img_url}}" class= "rounded-full member-img h-12 w-12 object-cover flex-shrink-0" alt="">
            <div class="mx-4">
                <p class="member-name mt-1 text-md font-medium leading-4">{{user.account.name}}</p>
                <p class="member-desg text-xs font-light">Associate Project Manager | Google</p>
            </div>
        </div>
        <div>
            <button class="member-follow bg-accent py-0.5 px-5 text-white text-sm rounded">Follow</button>
        </div>
    </div>
</template>
<script type="text" id="group-id">{{group.id}}</script>


{% block scripts %}
    <script src="/static/scripts/groups.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6"></script>
    <script>
        $(document).ready(function(){
            const grp_id = $('#group-id').text();
            let members=[];
            let fuse = false;
            let section_vis={};
            $.ajax({
                type:'POST',
                url: `/groups/get-members/${grp_id}/`,
                dataType: 'json',
                success: (data)=>{
                    console.log(data);
                    let ctr=0;
                    for( type in data ){
                        data[type].forEach(ele => {
                            let temp = document.getElementById("member-entry-temp");
                            let p = temp.content.cloneNode(true);
                            $('.member-name',p).text(ele.name);
                            $('.member-img',p).attr('src',ele.profile_img);
                            if(ele.is_followed){
                                $('.member-follow',p).addClass('hidden');
                            }
                            $(`#members-${type}`).append(p);
                            $(`.three-member-imgs img:eq( ${ctr++} )`).attr('src',ele.profile_img);
                            members.push({...ele, type:type});
                        });
                        if(!data[type].length){
                            $(`#members-${type}`).parent().addClass('hidden');
                            section_vis[`members-${type}`]=false;
                        }else{
                            section_vis[`members-${type}`]=true;
                        }
                    }
                    if(ctr<3){
                        for(let i=3; i>ctr; i--){
                            $(`.three-member-imgs img:eq( ${i-1} )`).addClass('hidden');
                        }
                    }
                    fuse = new Fuse(members, {keys:['name']});
                },
                error: (e,f)=>{
                    console.log(f);
                }
            })
            
            $('#member-search-input').on('input change', function(e){
                if(!fuse)return;
                if(this.value.length>=3){
                    $('.members-section').parent().addClass('hidden');
                    $('#members-results').parent().removeClass('hidden');
                    $('#members-results').html("");
                    const res=fuse.search(this.value);
                    if(res.length === 0){
                        $('#members-results').html('<p class="text-lg text-gray-500 text-center">No Results</p>');
                    }
                    res.forEach((ele)=>{
                        let temp = document.getElementById("member-entry-temp");
                        let p = temp.content.cloneNode(true);
                        $('.member-name',p).text(ele.item.name);
                        $('.member-img',p).attr('src',ele.item.profile_img);
                        if(ele.item.is_followed){
                            $('.member-follow',p).addClass('hidden');
                        }
                        $('#members-results').append(p);
                    })
                }else{
                    $('.members-section').each((ind,ele)=>{
                        if(section_vis[ele.id]){
                            $(ele).parent().removeClass('hidden');
                        }
                        $('#members-results').parent().addClass('hidden');
                    })
                }
            })
        })
    </script>
{% endblock %}

groups/templates/user_groups.html
<div class="w-full py-5 px-8 bg-white rounded-md mt-5 overflow-hidden">
    <p class="text-md">Groups you are part of:</p>
    <div class="mt-7 relative">
        {% for group in user.account.groups.all %}
        <a href="{% url 'groups:group' group.id %}" class="user-group cursor-pointer flex mt-5 items-stretch {%if forloop.counter > 3 %}hidden{%endif%}" 
        style="height: 58px;">
            <img class="object-cover rounded-sm flex-shrink-0" style="width: 84px;" src="{{group.cover_image.url}}">
            <div class="ml-4 flex flex-col">
                <p class="text-md font-medium flex-shrink overflow-hidden leading-5" title="{{group.title}}">{{group.title}}</p>
                <p class="text-xs text-gray-900">{{group.member_count}} Members</p>
            </div>
        </a>
        {% empty %}
        <p class="text-gray-500 text-center">None</p>
        {% endfor %}
        {% if user.account.groups.all|length > 3%}
        <p id="user-group-exp" class="text-accent text-xs mt-5 cursor-pointer">View More</p>
        {% endif%}
        <div class="absolute -right-10 top-0 h-full w-28 bg-gradient-to-r from-transparent to-white"></div>
    </div>
</div>

<script>
    $('#user-group-exp').on('click', function(e){
        $('.user-group').removeClass('hidden');
        $(this).addClass('hidden');
    })
</script>