alumniportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static #
from django.conf import settings #

urlpatterns = [
    path('admin-site/', admin.site.urls),
    path('admin/',include('adminPortal.urls') ),
    path('',include('users.urls')),
    path('chat/',include('chat.urls')),
    path('post/', include('post.urls')),
    path('faq/', include('faq.urls')),
    path('groups/', include('groups.urls')),
    path('events/', include('events.urls')),
]
if settings.DEBUG: #
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.index ,name='faq'),
    path('create-question/', views.create_question, name='create_question'),
    path('load-question/<index>', views.load_question, name='load_question'),
    path('question/<id>/', views.question_detail, name='detail_question'),
    path('create-ans/<id>/', views.create_answer, name='create_answer'),
    path('ans-from-alumni', views.get_best4, name='ans-from-alumni'),
    path('upvote/', views.upvote, name='upvote'),
    path('downvote/', views.downvote, name='downvote'),
    path('accept-answer/', views.accept_answer, name='accept-answer'),
    path('delete/<id>/', views.delete_faq, name='delete-faq'),
    path('report/<id>/', views.report_faq, name='report-faq'),
]

post/urls.py
from django.contrib import admin
from django.urls import path, re_path ,include
from . import views
from django.views.decorators.csrf import csrf_exempt
app_name='post'

urlpatterns=[
    path('create-post/', views.create_post ,name='create_post'),
    path('delete/', csrf_exempt(views.delete_post) ,name='post_delete'),
    path('report/', csrf_exempt(views.report_post) ,name='post_report'),
    path('update/<pk>/', views.update_post ,name='post_update'),
    path('detail/<pk>', views.post_details, name='post_detail'),
    path('load-feed/<index>',views.load_feed),
    path('load-post/<id>',views.individual_post),
    path('like-post/',views.like_post, name='like-post'),
    path('fileUpload/', csrf_exempt(views.upload_file_view)),
    path('imageUpload/', csrf_exempt(views.upload_image_view)),
    path('comment/<pk>/', views.comment, name='comment'),
    path('load-comment/<id>', views.load_comment),
    path('load-likes/<id>', views.load_likes),
]

post/models.py
from users.models import Account
from django.db import models
from groups.models import Group
import datetime
import json
class Post(models.Model):
    author=models.ForeignKey(Account,on_delete=models.CASCADE,related_name='posts',null=True)
    datetime=models.DateTimeField(auto_now_add=True)
    likes=models.ManyToManyField(Account,related_name='liked_posts')
    tags=models.ManyToManyField(Group, related_name='posts')
    content=models.JSONField(default=dict)
    reports=models.ManyToManyField(Account,related_name='reported_posts',blank=True)
    @property
    def rev_priority(self):
        age=(datetime.datetime.now()-self.datetime).total_seconds()//(3600*24)
        likes_count=len(self.likes.all())
        #in every 3 day group, the priority is decided by likes 
        return age//3 + 1/(likes_count or 1)

    def __str__(self):
        return self.author.name + "_" + str(self.id) 

class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments',null=True)
    author=models.ForeignKey(Account,on_delete=models.CASCADE,related_name='comments',null=True)
    content=models.CharField(max_length=500, null=True)
    create_date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.author.name + "_" + str(self.post.id) + '_' + str(self.id) 

post/forms.py
from .models import Post, Comment
from django import forms
from groups.models import Group

class PostForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(queryset=Group.objects.all(), label='', required = False)
    class Meta:
        model=Post
        fields=['content','tags']
        labels={'content':'','tags':''}

class CommentForm(forms.ModelForm):
    content= forms.CharField(label='', widget=forms.Textarea(attrs={'placeholder': ''}))
    class Meta:
        model=Comment
        fields=['content']
        labels={'content':''}

post/views.py
from groups.models import Group
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render ,redirect, get_object_or_404
from django.urls import reverse
import requests
from django.core.files.storage import FileSystemStorage
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.views.generic.detail import DetailView
from users.models import Account
from groups.models import Group
from time import sleep
# Create your views here.

def feed(request):
    groups = {}
    for group in Group.objects.all():
        groups[group.title]=group.id
    return render(request,'feed.html',{'postform': PostForm, 'tags':json.dumps(groups)})

def individualfeed(request,id):
    groups = {}
    return render(request,'feed.html',{'postform': PostForm, 'tags':json.dumps(groups),'id':id})

def create_post(request):
    if request.method=='POST':
        next = request.GET.get('next')
        postform=PostForm(request.POST)
        if postform.is_valid():
            post=postform.save(commit=False)
            post.author=request.user.account
            post.save()
            for tag in postform.cleaned_data.get('tags'):
                post.tags.add(tag)
            post.save()
            if next:
                return redirect(next)
            return redirect('home')
        else:
            return HttpResponse('form-inv')
    else:
        return HttpResponse('Invalid')

def post_details(request, pk):
    post=Post.objects.get(pk=pk)
    return render(request,'post_create.html',{'post':post})

class PostDetailView(DetailView):
    model=Post
    context_object_name='post'

def update_post(request, pk):
    if request.method=='POST':
        form=PostForm(request.POST)
        if form.is_valid():
            post=form.save(commit=False)
            post.user=request.user
            post.save()
            obj=get_object_or_404(Post, pk=pk)
            obj.delete()
        return redirect('post:mypage')
    else:
        obj=get_object_or_404(Post, pk=pk)
        form=PostForm(instance=obj)
        context={}
        context['form']=form
        return render(request, 'alumni_response/post_update.html', context)


def delete_post(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            post=get_object_or_404(Post,pk=request.POST.get('id'))
            if post.author!=request.user.account:
                return HttpResponse('forbidden', status=403)
            post.delete()
            return HttpResponse('success')
        return HttpResponse('badRequest', status=400)
    return HttpResponse('notLoggedIn',status=500)

def report_post(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            post=get_object_or_404(Post,pk=request.POST.get('id'))
            if request.user.account in post.reports.all():
                return HttpResponse('success')
            else:
                post.reports.add(request.user.account)
                post.save()
            return HttpResponse('success')
        return HttpResponse('badRequest', status=400)
    return HttpResponse('notLoggedIn',status=500)

import json
from urllib.parse import unquote
def upload_image_view(request):
    f=request.FILES['image']
    fs=FileSystemStorage()
    filename=str(f)
    fileurl='posts/'+ request.user.username + '/'
    filepath=fs.save(fileurl + filename,f)
    fileurl=unquote(fs.url(filepath))
    return JsonResponse({'success':1,'file':{'url':fileurl,'path':filepath}})

def upload_file_view(request):
    f=request.FILES['file']
    size=int(request.POST['size'])
    fs=FileSystemStorage()
    filename=str(f)
    fileurl='posts/'+ request.user.username + '/'
    filepath=fs.save(fileurl + filename,f)
    fileurl=unquote(fs.url(filepath))
    return JsonResponse({'success':1,'file':{'url':fileurl,"size":size,"name":str(f),"extension":fileurl.split('.')[-1], "path": filepath}})


import datetime
def get_feed(user,tagNames=[]):
    feed=[]
    tags=[]
    for tname in tagNames:
        tags.append(get_object_or_404(Group, title = tname))
    print(tags)
    if user.is_authenticated:
        follow_feed=[]
        following = list(user.account.following.all())
        following.append(user.account)
        for fuser in following:
            for post in fuser.posts.all():
                post_age = datetime.datetime.now()-post.datetime
                post_age = post_age.total_seconds() / 3600
                if post_age<=24:
                    if len(tags) and len(list(set(tags) & set(post.tags.all())))==0:
                        continue
                    follow_feed.append(post)
        follow_feed.sort(key=lambda x: x.datetime, reverse=True)
        general_feed=list(Post.objects.all())
        general_feed.sort(key=lambda x:x.rev_priority)
        feed=follow_feed[:]
        for post in general_feed:
            if post not in follow_feed:
                if len(tags) and len(list(set(tags) & set(post.tags.all())))==0:
                        continue
                feed.append(post)
    return feed


def like_post(request):
    if request.method == 'GET':
        post_id = request.GET['post_id']
        if request.user.is_authenticated:
            post=Post.objects.get(pk=post_id)
            acc=request.user.account
            if acc in post.likes.all():
                post.likes.remove(acc)
                msg="unliked"
            else:
                post.likes.add(acc)
                msg="liked"
            post.save()
            return HttpResponse(msg,status=200)
        else:
            return HttpResponse("Not Logged in!", status=500)
    else:
        return HttpResponse("unsuccessful", status=500)


from rest_framework import serializers
import json

class PostSerializer(serializers.ModelSerializer):
    id=serializers.SerializerMethodField()
    author = serializers.SerializerMethodField()
    like_count = serializers.SerializerMethodField()
    comment_count = serializers.SerializerMethodField()
    datetime=serializers.DateTimeField(format="%d %b,%Y %I:%M %p")
    class Meta:
        model = Post
        fields = ['author','like_count','datetime','content','id','comment_count']
    def get_author(self, post):
        if post.author:
            author={}
            author['name']=(' ').join([ x.capitalize() for x in post.author.name.split()])
            author['profile_img']= post.author.profile_img_url
            author['username']=post.author.user.username
            author['desg']=post.author.designation.title + " | " + post.author.organization.name
            return author
        else:
            return 'Anonymous'
    def get_like_count(self,post):
        return len(post.likes.all())
    def get_comment_count(self,post):
        return len(post.comments.all())
    def get_id(self,post):
        return post.pk






def load_feed(request,index):
    load_count=5
    index=int(index)
    user=request.user
    if not user.is_authenticated:
        return HttpResponse(json.dumps({'error':'Not Logged In'}),status=500)
    tags=[]
    if request.method == 'POST':
        tags = json.loads(request.POST.get('tags'))

    feed=get_feed(user,tags)
    posts=[]
    if len(feed)>index*load_count:
        for post in feed[index*load_count:min(len(feed),load_count*(index+1))]:
            print(post.content)
            data=PostSerializer(post).data
            data['is_liked']=user.account in post.likes.all()
            posts.append(data)
        return HttpResponse(json.dumps(posts),status=200)
    else:
        return HttpResponse(json.dumps({'error':'No more posts'}),status=500)

def individual_post(request,id):
    id=int(id)
    user=request.user
    if not user.is_authenticated:
        return HttpResponse(json.dumps({'error':'Not Logged In'}),status=401)
    post = Post.objects.get(id=id)
    data=PostSerializer(post).data
    return HttpResponse(json.dumps(data),status=200)



def comment(request, pk):
    if request.method=='POST':
        commentform=CommentForm(request.POST)
        post=get_object_or_404(Post, pk=pk)
        if commentform.is_valid():
            comment=commentform.save(commit=False)
            comment.post=post
            comment.author=request.user.account
            comment.save()
            return HttpResponse('success')
            # return HttpResponse(json.dumps(comment), status=200)
        else:
            return HttpResponse('form-inv', status=500)
    else:
        return HttpResponse('Invalid', status=500)


def load_comment(request, id):
  
    # comments=Comment.objects.all().filter(pk=id)
    comments=[]
    for comment in Post.objects.get(pk=id).comments.all():
        dic={}
        dic['author']=comment.author.name
        dic['profile_img']=comment.author.profile_img_url
        dic['create_date']=comment.create_date.strftime("%d/%m/%y")
        dic['content']=comment.content
        comments.append(dic)
    print(comments)
    return HttpResponse(json.dumps(comments), status=200)


def load_likes(request, id):
    likes=[]
    for like in get_object_or_404(Post, pk=id).likes.all():
        dic={}
        dic['author']=like.name
        dic['username']=like.user.username
        dic['profile_img']=like.profile_img_url
        likes.append(dic)
    return HttpResponse(json.dumps(likes), status=200)

post/templates/comment.html
<div id="comment-box" class="bg-white md:rounded p-4 w-full md:w-3/5 lg:w-2/5 h-screen md:h-5/6 lg:max-w-screen-sm flex flex-col justify-center" style="display:none;" >
    <div class="flex justify-between items-center m-2">
        <p class="text-xl">Comments</p>
        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg" class="close-overlay cursor-pointer">
            <path opacity="0.8" d="M1 13L13 1M1 1L13 13" stroke="#111827" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>   
    </div> 
    <p id="no-comment-msg" class="text-lg text-gray-400 text-center mt-5">No Comments :(</p>
    <div id="comment-box-content" class="mt-4 flex flex-col flex-1 w-full px-5 items-start overflow-scroll">

    </div>
    <form method="POST" id="comment-form" class="flex items-center w-full mt-3">
        {% csrf_token %}
        <div class=" bg-gray-100 p-2 flex-1 flex">
            <textarea name="content" type="text" id="comment-form-input" class="bg-transparent flex-1" style="min-height: 24px; height: 24px;"></textarea>
        </div>
        <button id="comment-form-submit" class="py-1 px-6 ml-5 text-white text-lg bg-accent rounded">Post</button>
    </form>
</div>
<template id="comment-template">
    <div class="comment flex items-start my-4">
        <div class="rounded-full h-12 w-12 overflow-hidden flex items-center justify-center flex-shrink-0">
            <img class="comment-author-img object-cover h-12 w-12" src="" alt="">
        </div>
        <div class="flex flex-col ml-4">
            <div class="comment-body bg-gray-100 rounded-lg py-2 px-4 w-auto">
                <p class="comment-author text-lg">Arjun Dey</p>
                <p class="comment-content text-gray-500" style="word-break: break-word;">Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam libero a enim beatae assumenda dolores laudantium quis id consequuntur rem nobis quos, qui aut adipisci, ut cum reiciendis esse quod?</p>
            </div>
            <!-- <div class="comment-date self-end text-xs text-gray-500 mt-1"></div> -->
        </div>
    </div>
</template>

<script>
    var tmp=document.createElement('div');
    document.body.appendChild(tmp);
    tmp.setAttribute('id','comment-resize-helper');
    let textarea = document.querySelector("#comment-form-input");
    $('#comment-form-input').on("input", function(e){
        tmp.setAttribute('style',`width:${this.clientWidth}px;`);
        tmp.innerHTML=this.value;
        this.style.height = Math.max(24, Math.min(96,tmp.clientHeight)) + "px";

    }); 
</script>

post/templates/post_create.html
<div id="post-form-area" class="bg-white md:rounded px-6 py-5 w-full md:w-3/5 lg:w-2/5 md:h-4/5 h-fullscreen flex flex-col" style="display:none;">
    <div class="flex justify-between items-center">
        <p class="text-xl">Create a post</p>
        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg" class="close-overlay cursor-pointer">
            <path opacity="0.8" d="M1 13L13 1M1 1L13 13" stroke="#111827" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>   
    </div>
    <div class="flex items-center mt-8">
        <div class="flex items-center">
            <img src="{{user.account.profile_img_url}}" class= "rounded-full h-12 w-12 object-cover flex-shrink-0" alt="">
            <p class="text-md sm:text-xl ml-3">{{user.account.name}}</p>
        </div>
        <!-- <div class="bg-accent-mid rounded px-3 py-0.5 flex items-center">
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M14.75 8C14.75 11.7279 11.7279 14.75 8 14.75M14.75 8C14.75 4.27208 11.7279 1.25 8 1.25M14.75 8H1.25M8 14.75C4.27208 14.75 1.25 11.7279 1.25 8M8 14.75C9.24264 14.75 10.25 11.7279 10.25 8C10.25 4.27208 9.24264 1.25 8 1.25M8 14.75C6.75736 14.75 5.75 11.7279 5.75 8C5.75 4.27208 6.75736 1.25 8 1.25M1.25 8C1.25 4.27208 4.27208 1.25 8 1.25" stroke="#111827" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            <p class="text-md mx-1">Anyone</p>   
            <svg width="8" height="4" viewBox="0 0 8 4" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M4 4L0.535898 0.25L7.4641 0.25L4 4Z" fill="black"/>
            </svg>
        </div> -->
    </div>
    <div class="flex-grow mt-7 flex flex-col overflow-y-scroll">
        <form method="POST" action="{% url 'post:create_post' %}" id="post-form" class="hidden">
            {% csrf_token %}
            {{postform}}
        </form>    
        <textarea name="" id="post-textarea" placeholder="Write something..." class="text-md h-20 flex-shrink-0 p-2"></textarea>
        <div id="post-attach-prev" class="flex flex-col w-full items-center">
            
        </div>
        <img id="post-image-prev" src="" alt="" class="object-contain my-3 hidden">
        <input type="file" id="post-image-input" class="hidden" accept="image/*">
        <input type="file" id="post-file-input-1" class="post-file-input hidden">
        <input type="file" id="post-file-input-2" class="post-file-input hidden">
    </div>
    <div class="flex justify-between items-center mt-5">
        <div class="flex items-stretch h-10">
            <div class="flex rounded items-center mx-2 sm:mx-4">
                <svg width="26" height="25" viewBox="0 0 26 25" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M13.0002 22.7581L13.0002 2.2732M2.75781 12.5156L23.2427 12.5156" stroke="#4150D7" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>    
            </div>
            <div id="post-add-image" class="flex px-3.5 rounded items-center mx-2 sm:mx-4 bg-gray-200 cursor-pointer">
                <svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1 13L5.58579 8.41421C6.36683 7.63317 7.63316 7.63316 8.41421 8.41421L13 13M11 11L12.5858 9.41421C13.3668 8.63317 14.6332 8.63316 15.4142 9.41421L17 11M11 5H11.01M3 17H15C16.1046 17 17 16.1046 17 15V3C17 1.89543 16.1046 1 15 1H3C1.89543 1 1 1.89543 1 3V15C1 16.1046 1.89543 17 3 17Z" stroke="#111827" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>   
            </div>
            <div id="post-add-attach" class="flex px-3.5 rounded items-center mx-2 sm:mx-4 bg-gray-200 cursor-pointer relative">
                <svg width="16" height="20" viewBox="0 0 16 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M3 19H13C14.1046 19 15 18.1046 15 17V7.41421C15 7.149 14.8946 6.89464 14.7071 6.70711L9.29289 1.29289C9.10536 1.10536 8.851 1 8.58579 1H3C1.89543 1 1 1.89543 1 3V17C1 18.1046 1.89543 19 3 19Z" stroke="#111827" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>     
                <div id="post-rem-attach" class="absolute bottom-1.5 right-2 text-white text-xs rounded-full bg-gray-500 w-3 h-3 flex items-center justify-center" style="font-size: 10px;">2</div>               
            </div>
        </div>
        <div id="post-form-submit" class="text-accent border-accent px-7 border-2 border-solid rounded">Post</div>
    </div>
</div>
<pre id="tag-list" class="hidden">{{tags}}</pre>
<template id="attach-prev-temp">
    <div class="attach-prev-wrapper mt-2 h-15 w-4/5 p-3 bg-gray-100 rounded flex items-center justify-between">		
        <div class="flex items-center">
            <img class = "attach-thumb h-10 w-10" src="">
            <div class = "ml-2">
                <p class = "attach-title text-md text-gray-500"></p>
                <p class = "attach-size text-sm text-gray-400"></p>
            </div>
        </div>
        <svg width="30" height="30" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg" class="attach-remove p-2 rounded-full hover:bg-gray-200 cursor-pointer">
            <path opacity="0.8" d="M1 13L13 1M1 1L13 13" stroke="#111827" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
    </div>
</template>

{% block scripts %}
    <script src="/static/scripts/post-create.js"></script>
{% endblock %}

post/templates/post_create2.html
<div id="post-form-area" class="bg-white rounded p-4 w-full lg:w-2/5" style="max-width: 700px;">
    <form method="POST" action="{% url 'post:create_post' %}" id="post-form">
        {% csrf_token %}
        {{postform.media}}
        {{postform.as_p}}
        <input type="file" name="img" style="display: none;">
    </form>
    <button id="post-form-submit"
        style="font-size: 18px; color:white; background: rgb(67, 79, 214); border: none; padding: 5px; width: 120px; margin-top: 10px;">Post</button>
</div>
<template>
    <div class="cdx-block image-tool image-tool--filled">
        <div class="image-tool__image">
            <div class="image-tool__image-preloader"></div>
            <img class="image-tool__image-picture">
        </div>
        <div class="cdx-input image-tool__caption" contenteditable="true" data-placeholder="Caption"></div>
        <div class="cdx-button"><svg width="20" height="20" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M3.15 13.628A7.749 7.749 0 0 0 10 17.75a7.74 7.74 0 0 0 6.305-3.242l-2.387-2.127-2.765 2.244-4.389-4.496-3.614 3.5zm-.787-2.303l4.446-4.371 4.52 4.63 2.534-2.057 3.533 2.797c.23-.734.354-1.514.354-2.324a7.75 7.75 0 1 0-15.387 1.325zM10 20C4.477 20 0 15.523 0 10S4.477 0 10 0s10 4.477 10 10-4.477 10-10 10z">
                </path>
            </svg> Select an Image</div>
    </div>
</template>

<script type="text/javascript">
    //TO PREVENT EDITORJs FROM UPLOADING FILES BEFORE ACTUAL POST
    let imgCount=0;
    $(window).on('load', function () {
        //to set the preview image
        $('[data-editorjs-wrapper=""]').bind('DOMSubtreeModified', function(){
            if($('.image-tool__image-preloader').length>imgCount){
                var bgimg=$('.image-tool__image-preloader')[imgCount].style.backgroundImage;
                if(bgimg!=''){
                    bgimg=bgimg.substring(5,bgimg.length-2);
                    if($('.image-tool__image-picture').length!=0){
                        if($('.image-tool__image-picture')[imgCount].getAttribute('src').startsWith('/media/')){
                            $('.image-tool__image-picture')[imgCount].setAttribute('src',bgimg);
                            imgCount++;
                        }
                    }
                }
                
            }
        })

        //overiding the form submit to upload the files first
        $('#post-form-submit').click(function(){
            //If there are no files to upload, submit immediately
            if(attaches.size + images.size == 0){
                $('#post-form').submit();
                return;
            }

            let ctr=0,index=0;
            let editorData=JSON.parse($('#id_content').val());
            attaches.forEach(function(ele){
                console.log(ele);
                let editorData=JSON.parse($('#id_content').val());
                let fileBlocks=editorData.blocks.filter(b=>b.type=='Attaches');
                let fileUrl=fileBlocks[index].data.file.url.split('/');
                fd = new FormData();
                fd.append("file", ele,fileUrl[ fileUrl.length -1 ]);
                fd.append("size",ele.size);
                $.ajax({
                    type: "POST",
                    url:'/post/fileUpload/',
                    data: fd,
                    processData: false,
                    contentType: false,
                    success: function(data){
                        ctr++;
                        if(ctr==attaches.size+images.size){
                            console.log('done');
                            $('#post-form').submit();
                        }
                    }
                })
                index++;
            })
            index=0;
            images.forEach(function(ele){
                console.log(ele);
                let imgBlocks=editorData.blocks.filter(b=>b.type=='Image');
                let imgUrl=imgBlocks[index].data.file.url.split('/');
                fd = new FormData();
                fd.append("image", ele,imgUrl[ imgUrl.length -1 ]);
                $.ajax({
                    type: "POST",
                    url:'/post/imageUpload/',
                    data: fd,
                    processData: false,
                    contentType: false,
                    success: function(data){
                        ctr++;
                        if(ctr==attaches.size+images.size){
                            console.log('done');
                            $('#post-form').submit();
                        }
                    }
                })
                index++;
            })
        });

        let attaches=new Set();
        let images=new Set();
        let dummyFile=new Blob(['dummyFile'],{type : 'text/html'});
        //extract file from editorjs whenever it does a mock upload
        //editorjs appends a temp input to body whenever it attempts to upload
        $('body').bind('DOMSubtreeModified', function(){
            if($('body>input[type=file][accept="*"]').length>0){
                $('body>input[type=file][accept="*"]').change(function(e){
                    console.log(e.target.files);
                    attaches.add(e.target.files[0]);
                })
            }
            if($('body>input[type=file][accept="image/*"]').length>0){
                $('body>input[type=file][accept="image/*"]').change(function(e){
                    console.log(e.target.files);
                    images.add(e.target.files[0]);
                })
            }
        })

        $('.codex-editor__redactor').css('padding-bottom','10px');
        $('.codex-editor__redactor').css('height','500px');
        $('.codex-editor__redactor').css('max-height','60vh');
        $('.codex-editor__redactor').css('margin','0');
        $('.codex-editor__redactor').css('overflow-y','scroll');

    })

</script>