alumniportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static #
from django.conf import settings #

urlpatterns = [
    path('admin-site/', admin.site.urls),
    path('admin/',include('adminPortal.urls') ),
    path('',include('users.urls')),
    path('chat/',include('chat.urls')),
    path('post/', include('post.urls')),
    path('faq/', include('faq.urls')),
    path('groups/', include('groups.urls')),
    path('events/', include('events.urls')),
]
if settings.DEBUG: #
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.index ,name='faq'),
    path('create-question/', views.create_question, name='create_question'),
    path('load-question/<index>', views.load_question, name='load_question'),
    path('question/<id>/', views.question_detail, name='detail_question'),
    path('create-ans/<id>/', views.create_answer, name='create_answer'),
    path('ans-from-alumni', views.get_best4, name='ans-from-alumni'),
    path('upvote/', views.upvote, name='upvote'),
    path('downvote/', views.downvote, name='downvote'),
    path('accept-answer/', views.accept_answer, name='accept-answer'),
    path('delete/<id>/', views.delete_faq, name='delete-faq'),
    path('report/<id>/', views.report_faq, name='report-faq'),
]

faq/models.py
from users.models import Account
from django.db import models

from groups.models import Group

import datetime

class Question(models.Model):
    author = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='questions')
    content = models.TextField(blank=False)
    posted_on = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Group, related_name='questions')
    views = models.IntegerField(default=0)
    reports = models.ManyToManyField(Account, related_name='reported_faqs', blank=True)

    def __str__(self):
        return self.author.name + "_" + str(self.id)

    @property
    def ans_count(self):
        return len(self.answers.all())

    @property
    def rev_priority(self):
        timediff = datetime.datetime.now() - self.posted_on
        return timediff.total_seconds()//3600 + 1 / (self.views or 1)


class Answer(models.Model):
    author = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='answers')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    posted_on = models.DateTimeField(auto_now_add=True)
    upvotes = models.ManyToManyField(Account,related_name='upvoted_answer')
    downvotes = models.ManyToManyField(Account,related_name='downvoted_answer')
    accepted = models.BooleanField(default=False)
    content = models.TextField(blank=False)

    def __str__(self) -> str:
        return self.author.name + "_q:" + str(self.question.id) + "_" + str(self.id)

    @property
    def rev_priority(self):
        if self.accepted:
            return 1
        return 2 + 1 / (self.upvotes.all().count() or 1)

    def upvote_count(self):
        return self.upvotes.all().count()

    def downvote_count(self):
        return self.downvotes.all().count()
    

faq/forms.py
from django.db.models import fields
from .models import Answer, Question
from django import forms

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['content']

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']

faq/views.py
from django.http import HttpResponseBadRequest, HttpResponseNotAllowed
from groups.models import Group
from post.views import comment
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from rest_framework import serializers

from .forms import QuestionForm, AnswerForm
from .models import Answer, Question
from groups.models import Group

import json, datetime

# Create your views here.
def index(request):
    return render(request, 'faq.html')

def create_question(request):
    if request.method == "POST":
        # create a QuestionForm instance from POST data
        question_form = QuestionForm(request.POST) 

        if question_form.is_valid():
            # create a new Question using question_form and dont commit to database.
            new_question = question_form.save(commit=False)
            new_question.author = request.user.account
            new_question.save()
            if request.POST.get("tag"):
                new_question.tags.add(request.POST.get("tag"))
                new_question.save()
            return redirect('faq:faq')
        else:
            ##################################################
            ##################################################
            ### DURING DEPLOYMENT RETURN CUSTOM ERROR PAGE ###
            ##################################################
            ##################################################
            return HttpResponse("Error in Question Form!")
    else:
        ####################################
        ####################################
        ### DURING DEPLOYMENT RETURN 404 ###
        ####################################
        ####################################
        return HttpResponse("No Post Request")

def create_answer(request, id):
    if request.method == "POST":
        ans_form = AnswerForm(request.POST)
        if ans_form.is_valid():
            new_ans = ans_form.save(commit=False)
            new_ans.author = request.user.account
            new_ans.question = get_object_or_404(Question, pk=id)
            new_ans.save()
            return redirect('faq:detail_question', id=id)
        else:
            ##################################################
            ##################################################
            ### DURING DEPLOYMENT RETURN CUSTOM ERROR PAGE ###
            ##################################################
            ##################################################
            print(ans_form.errors)
            return HttpResponse("Error in Answer Form!")
    else:
        ####################################
        ####################################
        ### DURING DEPLOYMENT RETURN 404 ###
        ####################################
        ####################################
        return HttpResponse("No Post Request")

def question_detail(request, id):
    question = get_object_or_404(Question, pk = id)
    answers = list(question.answers.all())
    answers.sort(key=lambda x: x.posted_on, reverse=True)
    answers.sort(key=lambda x: x.rev_priority)
    context = {
        'question': question,
        'answers': answers,
    }
    return render(request, 'question_detail.html', context);

class QuestionSerializer(serializers.ModelSerializer):
    ans_count = serializers.SerializerMethodField()
    answers = serializers.SerializerMethodField()
    author = serializers.SerializerMethodField()
    posted_on = serializers.DateTimeField(format="%d %b %Y")

    class Meta:
        model = Question
        fields = ['ans_count', 'answers', 'author', 'content', 'posted_on', 'id', 'views']

    def get_ans_count(self, obj):
        return int(obj.ans_count)
    
    def get_answers(self, obj):
        all_answers = list(obj.answers.all())
        all_answers.sort(key=lambda x: x.posted_on, reverse=True)
        all_answers.sort(key=lambda x: x.rev_priority)
        answer = {}
        if len(all_answers):
            answer['name'] = all_answers[0].author.name
            answer['profile_img'] = all_answers[0].author.profile_img_url
            answer['content'] = all_answers[0].content
        return answer

    def get_author(self, obj):
        if obj.author:
            author={}
            author['name']=(' ').join([ x.capitalize() for x in obj.author.name.split()])
            author['profile_img']= obj.author.profile_img_url
            author['username']=obj.author.user.username
            return author
        else:
            return 'Anonymous'

def get_questions(user, tagNames = []):
    questions=[]
    tags = []
    for tag in tagNames:
        tags.append(get_object_or_404(Group, title = tag))

    if user.is_authenticated:
        follow_questions = []
        following_users = list(user.account.following.all())
        following_users.append(user.account)
        for fuser in following_users:
            for question in fuser.questions.all():
                question_age = datetime.datetime.now()-question.posted_on
                question_age = question_age.total_seconds() / 3600
                if question_age<=24:
                    if len(tags) and len(list( set (tags) & set (question.tags.all()) )) == 0:
                        continue
                    follow_questions.append(question)
        follow_questions.sort(key=lambda x: x.posted_on, reverse=True)
        general_questions=list(Question.objects.all())
        general_questions.sort(key=lambda x:x.rev_priority)
        questions = follow_questions[:]
        for question in general_questions:
            if len(tags) and len(list( set (tags) & set (question.tags.all()) )) == 0:
                continue
            if question not in follow_questions:
                questions.append(question)
    return questions

def load_question(request, index):
    load_count=5
    index = int(index)

    if not request.user.is_authenticated:
        return HttpResponse(json.dumps({'error':'Not Logged In'}),status=500)

    tags = []
    if request.method == "POST":
        tags = json.loads(request.POST.get('tags'))
        questions = get_questions(request.user, tags)
        questions_to_be_sent=[]
        if len(questions) > index*load_count:
            for question in questions[index*load_count:min(len(questions),load_count*(index+1))]:
                data = QuestionSerializer(question).data
                questions_to_be_sent.append(data)
            return HttpResponse(json.dumps(questions_to_be_sent),status=200)
        else:
            return HttpResponse(json.dumps({'error':'No more posts'}),status=500)

    ##################################################
    ##################################################
    ### DURING DEPLOYMENT RETURN CUSTOM ERROR PAGE ###
    ##################################################
    ##################################################
    return HttpResponse("You aren't suppose to see this!")
    
def get_best4(request):
    if request.user.is_authenticated and request.method == "POST":
        questions = list(Question.objects.all())
        questions.sort(key=lambda x: x.posted_on, reverse=True)
        questions.sort(key=lambda x:x.rev_priority)
        count = 0
        final_questions = []
        for q in questions:
            data = QuestionSerializer(q).data
            if(data['answers'] != {}):
                final_questions.append(data)
                count += 1
            if count == 4:
                break
        return HttpResponse(json.dumps(final_questions), status=200);
    ##################################################
    ##################################################
    ### DURING DEPLOYMENT RETURN CUSTOM ERROR PAGE ###
    ##################################################
    ##################################################
    return HttpResponse("You aren't suppose to see this!")

def upvote(request):
    if request.method == 'GET':
        ans_id = request.GET['answer_id']
        if request.user.is_authenticated:
            answer=Answer.objects.get(id=ans_id)
            acc=request.user.account
            if acc in answer.upvotes.all():
                answer.upvotes.remove(acc)
                msg="removed_upvote"
            else:
                answer.upvotes.add(acc)
                if acc in answer.downvotes.all():
                    answer.downvotes.remove(acc)
                    msg="removed_downvote_and_added_upvote"
                    return HttpResponse(msg,status=200)
                msg="added_upvote"
            answer.save()
            return HttpResponse(msg,status=200)
        else:
            return HttpResponse("Not Logged in!", status=500)
    else:
        return HttpResponse("unsuccessful", status=500)

def downvote(request):
    if request.method == 'GET':
        ans_id = request.GET['answer_id']
        if request.user.is_authenticated:
            answer=Answer.objects.get(id=ans_id)
            acc=request.user.account
            if acc in answer.downvotes.all():
                answer.downvotes.remove(acc)
                msg="removed_downvote"
            else:
                answer.downvotes.add(acc)
                if acc in answer.upvotes.all():
                    answer.upvotes.remove(acc)
                    msg="removed_upvote_and_added_downvote"
                    return HttpResponse(msg,status=200)
                msg="added_downvote"
            answer.save()
            return HttpResponse(msg,status=200)
        else:
            return HttpResponse("Not Logged in!", status=500)
    else:
        return HttpResponse("unsuccessful", status=500)


def accept_answer(request):
    if request.method == "GET":
        ans_id = request.GET['answer_id']
        ques_id = request.GET['question_id']
        if request.user.is_authenticated:
            answer=Answer.objects.get(id=ans_id)
            question=Question.objects.get(id=ques_id)

faq/templates/alumni_answers.html
<div class="alumni-answers rounded w-full bg-white py-4 px-4 shadow-lg my-5">
    <div class="flex justify-between items-center w-full">
        <div class="flex items-center">
            <svg width="16" height="16" viewBox="0 0 13 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M5.33341 2.33334H2.00008C1.2637 2.33334 0.666748 2.93029 0.666748 3.66667V11C0.666748 11.7364 1.2637 12.3333 2.00008 12.3333H9.33341C10.0698 12.3333 10.6667 11.7364 10.6667 11V7.66667M9.72394 1.39052C10.2446 0.869825 11.0889 0.869825 11.6096 1.39052C12.1303 1.91122 12.1303 2.75544 11.6096 3.27614L5.8857 9H4.00008L4.00008 7.11438L9.72394 1.39052Z" stroke="#111827" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            <p class="text-md font-medium ml-2">Answers from Alumni</p>
        </div>
        <a href="{% url 'faq:faq' %}" class="text-accent text-sm">View More</a>
    </div>

    <div id="target" class="mt-10">
        
    </div>

    <template id="popular-questions">
        <div class="accordion-entry w-full border-b-2 border-solid border-gray-200 my-2 accordion-entry-collapsed">
            <div class="accordion-question flex justify-between items-center p-2 cursor-pointer">
                <p class="question-content"> </p>
                <button class="accordion-expand w-5 h-5 focus:outline-none"><img src="/static/img/down-arrow.svg" alt=""></button>
            </div>
            <div class="accordion-answer">
                <p class="answer-content text-sm text-gray-500 m-2"> </p>
            </div>
        </div>
    </template>
</div>

<script id='csrf_token' type='text'>{{csrf_token}}</script>
<script>
    csrf_token = $("#csrf_token").text();
    $.ajax({
        type: "POST",
        url: "/faq/ans-from-alumni",
        data: {'csrfmiddlewaretoken': csrf_token},
        dataType: "json",
        success: function (data) {
            for (const question of data) {
                // clone of children of template subtree
                let qClone = $("#popular-questions").contents().clone(true);

                // modify the data
                $(".question-content", qClone).html(question.content);
                $(".answer-content", qClone).html(question.answers.content);
                
                // append clone to target
                $("#target").append(qClone);
            }

            // add event listners (from base.js )
            loadAccordion();
        },
        error: function (data) {
            console.log(data.responseJSON.error);
        },
    });
</script>

faq/templates/faq-content.html
<div id="faq-questions">
    <div id="no-post" class="flex rounded bg-white justify-center items-center h-100 p-10 flex-col shadow-lg my-10 hidden">
        <p class="text-lg text-gray-500">No Questions Yet</p>
        <p class="text-sm text-gray-400 mt-4"><b>Tip:</b> Ask a question</p>
    </div>
</div>

<div id="question-container">

</div>

<template id="question-template">
    <div class="faq rounded w-full bg-white py-4 px-3 shadow-lg my-10">
        <div class="faq-header w-full px-3 md:py-3 overflow-auto flex justify-between">
            <div class="flex justify-start flex-col w-full">
                <p class="question-content faq-question text-lg md:text-xl mt-1"></p>
                <div class="flex items-center justify-between mt-2">
                    <div class="text-sm text-gray-400">Posted by &nbsp;
                        <a class="question-author faq-author text-accent text-sm" href=""></a>
                    </div>
                    <a class="question-details text-accent text-sm text-right" href="">View Details</a>
                </div>
            </div>
            <!-- <div class="float-right flex flex-col items-end flex-shrink-0">
            </div> -->
        </div>
        <div class="faq-answers py-4 flex flex-col items-center pt-0">
            <!-- <p class="faq-no-ans text-gray-400 font-light my-3 w-full text-center hidden">No Answers</p> -->
            <!-- <p class="text-gray-400 text-sm w-full ml-5">Answers:-</p> -->
            <div class="answer-container px-3">
                
            </div>
        </div>
    </div>
</template>

<template id="answer-template">
    <div class="w-full">
        <div class="flex justify-between items-center py-3 px-3">
            <div class="flex items-center justify-start">
                <div class="rounded-full h-12 w-12 overflow-hidden flex items-center justify-center flex-shrink-0">
                    <img src="{{user.account.profile_img_url}}" class= "ans-img h-14 w-14 object-cover" alt="">
                </div>
                <div class="mx-4">
                    <p class="ans-author mt-1">{{user.account.name}}</p>
                    <p class="text-sm text-gray-400 mt-1">Associate Project Manager | Google</p>
                </div>
            </div>

        </div>
        <div class="">
            <p class="ans-content text-sm text-gray-500 m-2">In fermentum vehicula sem vitae eleifend. Nam pretium iaculis hendrerit. Nam in erat at elit ultricies tincidunt pharetra sit amet ante. Sed sed sem sit amet arcu laoreet finibus ac ac sem. </p>
        </div>
    </div>
</template>

<script id='faq_csrf_token' type='text'>{{csrf_token}}</script>


{% block scripts %}
    <script type="text" id="data-username">{{user.username}}</script>
    <script src="/static/scripts/faq.js"></script>
{% endblock %}

faq/templates/faq.html
{% extends "base.html" %}

{% block content %}
<div class="faq-ask rounded w-full bg-white py-7 px-5 shadow-lg my-5 flex justify-between items-center" >
    <form id="question_form" action="{% url 'faq:create_question' %}" class="flex items-center flex-grow" method="POST">
        {% csrf_token %}
        <img class="h-5 w-5" src="/static/img/pencil.svg" alt="">
        <input name="content" type="text" id="question-text" class="text-lg text-gray-600 mx-5 hidden md:block flex-grow"
         placeholder="Ask a Question" autocomplete="off" contenteditable>
         <button type="submit" class="bg-accent py-1 px-4 text-white text-md rounded">Ask</button>
        </form> 
</div>

<script class='faq-feed-tag' type='text'></script>

{% include "faq-content.html" %}

{% endblock %}



{% block right-pane %}
    {% include "alumni_answers.html" %}
    {% include 'suggestions.html'%}
{% endblock %}

{% block overlay %}
{% endblock%}

faq/templates/faq_create.html
<div class="faq-ask bg-white md:rounded px-6 py-5 w-full md:w-3/5 lg:w-2/5 md:h-3/5 h-fullscreen flex flex-col" style="display: none;">
    <div class="flex justify-between items-center">
        <p class="text-xl">Ask a Question</p>
        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg" class="close-overlay cursor-pointer">
            <path opacity="0.8" d="M1 13L13 1M1 1L13 13" stroke="#111827" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>   
    </div>
    <div class="flex justify-between items-center mt-8">
        <div class="flex items-center">
            <img src="{{user.account.profile_img_url}}" class= "rounded-full h-12 w-12 object-cover flex-shrink-0" alt="">
            <p class="text-md sm:text-xl ml-3">{{user.account.name}}</p>
        </div>
    </div>
    <form id="question_form" action="{% url 'faq:create_question' %}" class="flex-grow mt-4" method="POST">
        {% csrf_token %}
        <textarea id="question-text" name="content" class="text-lg w-full h-full h-20 flex-shrink-0 py-4 px-4 rounded-lg bg-gray-100 resize-none" placeholder="Write something here..." ></textarea>
    </form> 
    <button id="ask_button" class="bg-accent py-1 px-6 mt-4 text-white text-md rounded self-end">Ask</button>
</div>

{% block scripts %}
    <script>
        $(document).ready(function () {
            $(".create-question").click(function(e) {
                $('#overlay').css('display','flex');
                $(".faq-ask").css("display", "flex");
            });

            $("#ask_button").click(function (e) {
                e.preventDefault();
                if($("#question-text").val().length === 0) 
                    alert("Sorry, the question can't be empty!");
                else {
                    $("#question_form").submit(function(eventObj) {
                        let tag;
                        $('.faq-feed-tag').each((ind,ele)=>{
                            if(ele.textContent.length) {
                                tag = $(ele).attr('data-id');
                                console.log(tag);
                                $("<input />").attr("type", "hidden")
                                    .attr("name", "tag")
                                    .attr("value", tag)
                                    .appendTo("#question_form");
                            }
                        });
                        
                    });
                    $("#question_form").submit();
                }
            });
        });
    </script>
{% endblock %}

faq/templates/question_detail.html
{% extends "base.html" %}
{% block content %}
<div class="faq rounded w-full bg-white py-4 px-3 shadow-lg my-5 px-3">
  <div class="w-ful">
    <p class="ans-author text-xl font-medium mt-1 mx-2">{{question.content}}</p>
    <div class="flex justify-between items-center py-3 px-3">
      <div class="flex items-center justify-start">
        <img src="{{question.author.profile_img_url}}" class="ans-img h-9 w-9 object-cover rounded-full flex-shrink-0"/>
        <div class="ml-2">
          <p class="text-sm text-gray-500 mt-0.5" >{{question.author.name}}</p>
          <p class="text-xs font-light text-gray-500">
            {{question.author.designation.title}} | {{question.author.organization.name}}
          </p>
        </div>
      </div>
      <div class="flex flex-col items-end">
          <div class="relative overflow-visible ">
            <img src="/static/img/more.svg" alt="" class="faq-options-button cursor-pointer h-5 w-5">
            <div class="faq-options bg-white absolute top-6 right-0 shadow-lg w-32 right-0 px-1 py-1 border-2 border-gray-100 border-solid hidden">
                {% if question.author == user.account %}
                <div class="faq-delete text-sm text-gray-500 hover:bg-gray-100 py-2 px-1 flex items-center cursor-pointer" href="#" data-faq-id="{{question.id}}">
                    <img src="/static/img/delete.svg" class="h-4 -mt-0.5">
                    <p class="ml-2">Delete</p>
                </div>
				{% endif %}
                <div class="faq-report block text-sm text-gray-500 hover:bg-gray-100 py-2 px-1 flex items-center cursor-pointer" href="#" data-faq-id="{{question.id}}">
                    <img src="/static/img/innfo.svg" class="h-4 -mt-0.5">
                    <p class="ml-2">Report</p>
                </div>
            </div>
        </div>
        <p class="text-xs font-light text-gray-500 ">{{question.posted_on}}</p>
		<p id="answer-focus" class="text-sm mt-1 text-accent cursor-pointer">Answer</p>
      </div>
    </div>
  </div>
</div>
<!-- <p>Question: {{question.content}}</p> -->

{% for ans in answers %}
<div class="faq rounded w-full bg-white py-4 px-3 shadow-lg my-10 px-3">
  <div class="w-full">
    <div class="flex justify-between py-3 px-3">
      <div class="flex items-center justify-start">
        <div class=" rounded-full h-12 w-12 overflow-hidden flex items-center justify-center flex-shrink-0">
          <img src="{{ans.author.profile_img_url}}" class="ans-img h-14 w-14 object-cover"/>
        </div>
        <div class="mx-4">
          <p class="ans-author mt-1">{{ans.author.name}}</p>
          <p class="text-sm text-gray-400">
            {{ans.author.designation.title}} | {{ans.author.organization.name}}
          </p>
        </div>
      </div>
      <div class="flex flex-col">
        <p class="text-xs font-light text-gray-500 mt-2">{{ans.posted_on}}</p>
        {% if ans.accepted %}
        <div class="flex flex-row mt-1 justify-end">
          <svg width="15" height="15" xmlns="http://www.w3.org/2000/svg" fill="#00FF00" viewBox="0 0 24 24">
            <path stroke="#FFFFFF" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z" />
          </svg>
          <p class="text-xs font-light">Answer Accepted</p>
        </div>
        {% endif %}
      </div>
    </div>
    <div class="flex flex-row">
      <div class="flex flex-col my-2 mx-3">
        <div class="flex flex-row mb-1">
          <div class="upvote-btn" data-answer-id="{{ans.id}}">
            <svg id="upvote-btn-{{ans.id}}" width="20" height="20" xmlns="http://www.w3.org/2000/svg" class="close-overlay cursor-pointer {% if request.user.account in ans.upvotes.all %}svg-accent-u{% endif %}" fill="none" viewBox="0 0 24 24">
              <path opacity="0.8" stroke-linecap="round" stroke="#CCCCCC" stroke-linejoin="round" stroke-width="2" d="M5 15l7-7 7 7" />
            </svg>
          </div>
          <p id="upvote-value-{{ans.id}}" class="ml-1 text-sm text-gray-700 align-center">{{ans.upvote_count}}</p>
        </div>
        <div class="flex flex-row mb-1">
          <div class="downvote-btn" data-answer-id="{{ans.id}}">
            <svg id="downvote-btn-{{ans.id}}" width="20" height="20" xmlns="http://www.w3.org/2000/svg" class="close-overlay cursor-pointer {% if request.user.account in ans.downvotes.all %}svg-accent-d{% endif %}" fill="none" viewBox="0 0 24 24">
              <path opacity="0.8" stroke-linecap="round" stroke="#CCCCCC" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
            </svg>
          </div>
          <p id="downvote-value-{{ans.id}}" class="ml-1 text-sm text-gray-700 align-center">{{ans.downvote_count}}</p>
        </div>
        {% if request.user.account == ans.question.author %}
        {% if not ans.accepted %}
        <div class="flex flex-row mb-1">
          <div class="accept-btn" data-answer-id="{{ans.id}}" data-question-id="{{question.id}}">
            <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg" class="close-overlay cursor-pointer" fill="none" viewBox="0 0 24 24">
              <path opacity="0.5" stroke-linecap="round" stroke="#00FF00" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
            </svg>
          </div>
          <p class="ml-1 text-sm text-gray-700 align-center">Ok</p>
        </div>
        {% endif %}
        {% endif %}
      </div>
      <p class="ans-content text-sm text-gray-500 m-2">
        {{ans.content}}
      </p>
    </div>
  </div>
</div>
{% endfor %}


<div class="faq rounded w-full bg-white py-2 shadow-lg my-10">
  <div class="mx-4 border-solid border-b-2 border-gray-200 py-1 px-2">
    <p class="text-lg font-medium ans-author mt-1">Write an answer</p>
  </div>

  <form id="ans-form" action="{% url 'faq:create_answer' id=question.pk %}" method="POST" class="flex flex-col mx-4 mt-4 px-2">
    {% csrf_token %}

    <textarea class="w-full py-4 px-6 h-52 bg-gray-100 rounded-lg font-light" name="content" placeholder="Write something here..."></textarea>
    <button type="submit" id="ans-submit" class="bg-accent py-0.5 px-7 text-white mt-4 mb-2 rounded self-end">Post</button>
  </form>
  <input type="text" readonly hidden id="csrf-token" value="{{csrf_token}}">
</div>

{% endblock content %}

{% block right-pane %}
  {% include "alumni_answers.html" %}
{% endblock %}

{% block scripts %}
  <script>
    $(document).ready(function () {
		let csrf_token = $('#csrf-token').val();
		$("#ans-submit").click((e) => {
			e.preventDefault();
			if($("textarea", $("#ans-form")).val().length === 0) alert("Sorry, empty answer isn't accepted!");
			else {
			$("#ans-form").submit();
			}
		});

		$('#answer-focus').on('click', function(e){
			$('html, body').animate({
			scrollTop: $('#ans-form textarea').offset().top - 200
			}, 1000);
			setTimeout(()=>{
			$('#ans-form textarea')[0].focus();
			},1000);
		})

		$('.faq-options-button').on('click', function(){
			$('.faq-options',this.parentElement).toggleClass('hidden');
		} );

		$('.faq-delete').on('click', function(){
			let id = $(this).attr('data-faq-id');
			if (confirm('Are you sure you want to delete the question?')) {
				$.ajax({
					type: "POST",
					url: `/faq/delete/${id}/`,
					data: {'csrfmiddlewaretoken':csrf_token},
					success: function (data) {
						window.open(`/faq/`,"_self");
					},
					error: function (data) {
						alert(data);
					},
				});
			}
		});

		$('.faq-report').on('click', function(){
			let id = $(this).attr('data-faq-id');
			if (confirm('Are you sure you want to report the question?')) {
				$.ajax({
					type: "POST",
					url: `/faq/report/${id}/`,
					data: {'csrfmiddlewaretoken':csrf_token},
					success: function (data) {
						alert('Reported!')
					},
					error: function (data) {
						alert(data);
					},
				});
			}
		});
		

    });
  </script>
<script id='csrf_token' type='text'>{{csrf_token}}</script>
<script type="text" id="data-username">{{request.user.username}}</script>
<script src="/static/scripts/q_detail.js"></script>
{% endblock scripts %}